all:
  hosts:
#    node1:
#      ansible_host: TODO
#      ansible_user: TODO
#      ip: TODO
#      access_ip: TODO
  children:
    kube-master:
      hosts:
#        node1:
    kube-node:
      hosts:
#        node1:
    etcd:
      hosts:
#        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
